labring/laf

packages/system-client/src/views/account/sign-in.vue
packages/system-client/src/views/account/sign-up.vue

fix(client): fix log in word

---

.github/workflows/docker-images.yml

需要配置secrets DOCKER_USERNAME、DOCKER_PASSWORD
#120

feat: add auto build & push docker images by github actions

---

packages/web/package-lock.json
packages/web/package.json
packages/web/scripts/extend-route.ts
packages/web/scripts/utils.ts
packages/web/scripts/vite-plugin-vue-sfc-name.ts
packages/web/vite.config.ts

+ 编写vite插件，根据路径，自动给页面级组件统一命名
+ 同时修改编译时的路由元信息，使得组件名和路由信息进行关联
上面的举措用于方便后期支持多tab访问。

build: unify component name of pages

---

packages/gateway-controller/src/support/apisix-gateway-init.ts
packages/gateway-controller/src/support/apisix-gateway.ts
packages/gateway-controller/src/support/route.ts
packages/system-server/src/handler/website/domain-bind.ts
packages/system-server/src/handler/website/website-create.ts
packages/system-server/src/handler/website/website-delete.ts
packages/system-server/src/support/route.ts

feat: opt website domain

---

deploy/docker-compose/docker-compose.yml
docker-compose.yml
packages/gateway-controller/src/config.ts
packages/gateway-controller/src/index.ts
packages/gateway-controller/src/support/apisix-gateway-init.ts
packages/gateway-controller/src/support/apisix-gateway-utils.ts

feat: add ssl support

---

docs/.vitepress/config.js

fix: page route

---

packages/gateway-controller/src/index.ts
packages/gateway-controller/src/support/apisix-gateway-init.ts
packages/system-server/src/init.ts

fix: fix load ssl route error

---

packages/system-server/src/handler/application/remove.ts
packages/web/src/pages/apps/components/AppTable.vue

- add more `app.status` type. because backend cannot release `starting/etc...` status
those request will return 400 response
now disable it.
- add new tooltip for disable case, tell user the reason of why we
cannot release
- add popconfirm for this action, its danger action, we should reconfirm it
- allow created app delete

feat: add more app status process for release action

---

packages/web/src/pages/app/[appid]/cloudfunction/components/DebugPanel.vue
packages/web/src/pages/app/[appid]/cloudfunction/index.vue
packages/web/src/pages/app/[appid]/cloudfunction/logs/index.vue
packages/web/src/pages/app/[appid]/cloudfunction/triggers/[funcId].vue

1. 修复日志页面打不开的问题，现在 
是依据这个 `name` 来生成页面的路由 name，但是这个现在是菜单和路由公用，后面需要增加一个专门给 route 用的 name
2. 优化了下页面的显示，有些地方按扭太大，改成 size="small" 和 plain 样式

fix: 查看日志打不开

---

server/package-lock.json
server/package.json
server/src/applications/applications.service.ts
server/src/applications/entities/application.entity.ts
server/src/applications/entities/bundle.entity.ts
server/src/applications/entities/runtime.entity.ts
server/src/buckets/buckets.service.ts
server/src/buckets/entities/bucket.entity.ts
server/src/core/kubernetes.interface.ts
server/src/core/kubernetes.service.spec.ts
server/src/core/kubernetes.service.ts
server/src/functions/entities/function.entity.ts
server/src/functions/functions.service.ts

feat(server): add k8s patch method to k8s service

---

server/src/app.controller.ts
server/src/applications/applications.controller.ts
server/src/applications/applications.service.spec.ts
server/src/applications/applications.service.ts
server/src/applications/dto/create-application.dto.ts
server/src/applications/dto/update-application.dto.ts
server/src/applications/entities/application.entity.ts
server/src/constants.ts
server/src/core/kubernetes.service.spec.ts
server/src/core/kubernetes.service.ts

feat(server): impl application update & deletion APIs

---

server/src/app.controller.ts
server/src/applications/applications.controller.ts
server/src/buckets/buckets.controller.ts
server/src/functions/dto/create-function.dto.ts
server/src/functions/dto/update-function.dto.ts
server/src/functions/functions.controller.ts
server/src/functions/functions.service.ts

feat(server): impl cloud function update & deletetion apis

---

server/src/applications/application-task.service.ts
server/src/core/application.cr.service.ts
server/src/core/database.cr.service.ts
server/src/core/gateway.cr.service.ts
server/src/core/oss-user.cr.service.ts
server/src/instance/instance-task.service.ts
server/src/instance/instance.service.ts

fix(server): fix error log in server

---

core/controllers/gateway/apisix/ssl.go
core/controllers/gateway/apisix/ssl_test.go
core/controllers/gateway/controllers/domain_controller.go
core/controllers/gateway/controllers/gateway_controller.go

支持gateway配置证书
配置方式：
在系统命名空间下新增一个secret 命名为xxx
然后创建secret
```
kubectl create secret -n laf tls app-tls-secret --cert=/root/lafyun/certs/lafyun.cer --key=/root/lafyun/certs/lafyun.key
```
然后在创建domain的时候指定certConfigRef为xxx
TODO
监听secret变化的时候更新网关内ssl配置

feat: support gateway ssl

---

server/package-lock.json
server/package.json
server/src/applications/applications.controller.ts
server/src/applications/applications.module.ts
server/src/applications/applications.service.ts
server/src/main.ts

feat(server): add function debug token api

---

core/controllers/gateway/config/crd/bases/gateway.laf.dev_domains.yaml
core/controllers/gateway/config/crd/bases/gateway.laf.dev_gateways.yaml
core/controllers/gateway/config/crd/bases/gateway.laf.dev_routes.yaml
core/controllers/gateway/controllers/gateway_controller.go
core/controllers/gateway/deploy/manifests/deploy.yaml
deploy/build/charts/laf/charts/minio/templates/statefulset.yaml

fix(core): fix gateway bucket name issue & minio deploy domain config

---

web/public/locales/zh-CN/translation.json
web/src/apis/typing.d.ts
web/src/apis/v1/api-auto.d.ts
web/src/apis/v1/apps.ts
web/src/components/Editor/JsonEditor.tsx
web/src/hooks/useFuncitonCache.ts
web/src/pages/app/database/CollectionDataList/mods/ColPannel/index.tsx
web/src/pages/app/functions/index.tsx
web/src/pages/app/functions/mods/DebugPannel/index.tsx
web/src/pages/app/functions/mods/FunctionPanel/index.tsx
web/src/pages/app/functions/service.ts
web/src/pages/app/functions/store.ts

1. function debug
2. function compile
3. function codes support store in localstorage

feat(web): complete function compile

---

web/src/components/CopyText/index.tsx
web/src/pages/app/database/CollectionDataList/index.tsx
web/src/pages/app/database/CollectionDataList/mods/DataPannel/index.tsx
web/src/pages/app/database/CollectionListPanel/index.tsx
web/src/pages/app/database/store.ts
web/src/pages/app/functions/index.tsx
web/src/pages/app/functions/mods/DebugPannel/index.tsx

1. fix 云函数调试页面实际为 POST，显示为 GET
2. fix 云函数调试地址可隐藏，与调用地址一致且重复
1. fix 去除/ 隐藏 索引管理 和集合结构 页面元素
2. fix 空数据时，需要处理 disable

feat(web): fix functionPannel & dataPannel

---

web/src/pages/app/storages/mods/CreateFolderModal/index.tsx
web/src/pages/app/storages/mods/StorageListPanel/index.tsx
web/src/pages/app/storages/mods/UploadButton/index.tsx
web/src/pages/app/storages/store.ts

feat(web): disabled upload button when fileList is empty

---

web/src/components/EditableTable/EditableTr/index.tsx
web/src/components/EditableTable/NormalTr/index.tsx
web/src/components/EditableTable/index.tsx
web/src/layouts/Header/UserSetting/index.tsx
web/src/pages/app/setting/AppEnvList/index.tsx
web/src/pages/app/setting/PATList/index.tsx
web/src/pages/app/setting/PATList/service.ts
web/src/pages/app/setting/index.tsx
web/src/pages/app/storages/mods/FileList/index.tsx
web/src/pages/globalStore.ts

1. hide patList edit button
2. show copy token button when create
3. logout
4. add application aenvironment variable button (restart application)

feat(web): hide patList edit button & show copy token button

---

web/src/components/Editor/JsonEditor.tsx
web/src/components/Grid/index.tsx
web/src/components/Panel/index.tsx
web/src/pages/app/database/BottomPanel/index.tsx
web/src/pages/app/database/CollectionDataList/index.tsx
web/src/pages/app/database/CollectionListPanel/index.tsx
web/src/pages/app/database/index.tsx
web/src/pages/app/functions/index.tsx
web/src/pages/app/functions/mods/BottomPanel/index.tsx
web/src/pages/app/functions/mods/DebugPannel/index.tsx
web/src/pages/app/functions/mods/EditorPanel/index.tsx
web/src/pages/app/functions/mods/FunctionPanel/index.tsx
web/src/pages/app/functions/service.ts
web/src/pages/app/functions/store.ts
web/src/pages/app/logs/index.tsx
web/src/pages/app/storages/index.tsx
web/src/pages/app/storages/mods/StorageListPanel/index.tsx
web/src/pages/customSetting.ts

https://user-images.githubusercontent.com/972813/212052463-f4d6893c-e8b2-40cc-b11a-cc1509f309fa.mov

feat(web): support toggle panels in function page

---

web/public/locales/en/translation.json
web/public/locales/zh-CN/translation.json
web/public/locales/zh/translation.json
web/src/chakraTheme.ts
web/src/components/FileTypeIcon/index.tsx
web/src/components/Grid/index.tsx
web/src/components/MoreButton/index.tsx
web/src/hooks/useFunctionCache.ts
web/src/pages/app/database/service.ts
web/src/pages/app/functions/mods/DebugPanel/index.tsx
web/src/pages/app/functions/mods/DeployButton/index.tsx
web/src/pages/app/functions/mods/EditorPanel/index.tsx
web/src/pages/app/functions/mods/FunctionPanel/index.tsx
web/src/pages/app/storages/mods/StorageListPanel/index.tsx

fix(web): ui refactor, fix styles & tips

---

runtimes/nodejs/README.md
runtimes/nodejs/src/support/cloud-sdk.ts

After add custom env, can not get value from `cloud.env`
Fix this bug by use `...process.env` code
**Note: This fix haven't be fully test:**
Update environment variable will restart app container, this method(using telepresence intercept) can not restart local container

fix(runtime-nodejs): fix custom env unable to read

---

cli/src/command/application/index.ts
cli/src/command/function/index.ts
cli/src/command/storage/index.ts

fix(cli): fix some word case

---

web/public/locales/en/translation.json
web/public/locales/zh-CN/translation.json
web/public/locales/zh/translation.json
web/src/components/ConfirmButton/index.tsx
web/src/pages/app/setting/AppEnvList/index.tsx

https://user-images.githubusercontent.com/37979965/219876568-10fb0038-3626-4c92-a416-6c20c2473350.mov
1. Update env will restart application, this operation needs to remind the user
2. ComfirmButton Component default confirm text is `delete`, add an `option` variable named `confirmButtonText` to replace defaut text

feat(web): add confirm update env modal

---

web/src/apis/typing.d.ts
web/src/components/Editor/typesResolve/index.ts
web/src/pages/app/functions/store.ts

端口不是 80 和 443 的情况下为函数的 url 添加上端口

fix(web) : add port for functionUrl

---

deploy/build/charts/laf-server/templates/cert-issuer.yaml
server/src/constants.ts
server/src/gateway/apisix-crd.service.ts
server/src/gateway/apisix-custom-cert.service.ts
server/src/gateway/apisix.service.ts
server/src/gateway/gateway.module.ts
server/src/gateway/website-task.service.ts
server/src/instance/instance.service.ts
server/src/region/cluster/cluster.service.ts

Upgrade to this version from old version need apply a cert issuer:
```sh
kubectl apply -f - <<EOF
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
name: laf-issuer
spec:
acme:
server: https://acme-v02.api.letsencrypt.org/directory
email: admin@sealos.io
privateKeySecretRef:
name: letsencrypt-prod
solvers:
- http01:
ingress:
class: apisix
EOF
```

feat(server): support website custom domain ssl cert auto-gen

---

server/src/auth/dto/passwd-check.dto.ts
server/src/auth/user-passwd/user-password.controller.ts
server/src/auth/user-passwd/user-password.service.ts

1. Add an password route:  `/v1/auth/passwd/check`
return `true` or `false` to show whether user have set password
2. User can request `/v1/auth/passwd/reset` to set a password if haven't binded password
3. **Note**: user need `send reset sms code` first before reset password

feat(server): add check if password had binded

---

web/public/locales/en/translation.json
web/public/locales/zh-CN/translation.json
web/public/locales/zh/translation.json
web/src/chakraTheme.ts
web/src/chakraThemeDark.ts
web/src/components/InputTag/index.tsx
web/src/pages/app/functions/mods/FunctionPanel/index.tsx
web/src/pages/home/mods/CreateAppModal/index.tsx

https://user-images.githubusercontent.com/972813/227205239-381ba5bf-6ba0-47f5-be44-6741b8c09e62.mov

refactor(web): optimize the tag selection

---

deploy/build/charts/minio/values.yaml

Ref: https://nvd.nist.gov/vuln/detail/CVE-2023-28432

fix(deploy): upgrade minio version to fix CVE-2023-28432

---

web/public/locales/en/translation.json
web/public/locales/zh-CN/translation.json
web/public/locales/zh/translation.json
web/src/apis/typing.d.ts
web/src/pages/app/mods/SideBar/index.tsx
web/src/pages/app/setting/AppInfoList/index.tsx
web/src/pages/home/mods/List/index.tsx

feat(web): add region info on logo

---

web/src/pages/app/database/mods/AddRulesModal/index.tsx
web/src/pages/auth/signin/mods/LoginByPhonePanel/index.tsx
web/src/pages/home/mods/CreateAppModal/index.tsx
web/src/pages/home/mods/List/index.tsx
web/src/utils/request.ts

General business error handling

feat(web): common error handler

---

.github/workflows/build-sealos-cluster-image.yml
.github/workflows/dockerize-runtime-nodejs.yml
.github/workflows/e2e.yml
e2e/e2e.sh
e2e/f1-payload.json
e2e/f2-origin-payload.json
e2e/f2-update-payload.json

It has already been tested (triggered manually) in my repository: https://github.com/aFlyBird0/laf/actions/runs/4777850653

ci: init e2e(check deployment and app create)

---

.github/workflows/link-schedule.yml

If no broken links, no issue.
else, like this:

ci: report broken links as an issue

---

.github/workflows/e2e.yml
e2e/e2e.sh

1. wait api route in apisix ready
2. add more actions trigger
You can take a look at the execution result of this action. This is the result obtained when I temporarily changed the trigger condition to `pull request`: https://github.com/labring/laf/actions/runs/4800439541

ci(e2e): wait api route in apisix ready

---

web/src/components/Editor/JSONViewer.tsx
web/src/pages/app/database/CollectionListPanel/index.tsx
web/src/pages/app/database/PolicyListPanel/index.tsx
web/src/pages/app/functions/mods/FunctionPanel/index.tsx

refactor(web): text overflow ellipsis

---

web/src/apis/typing.d.ts
web/src/pages/app/functions/mods/DebugPanel/BodyParamsTab/index.tsx
web/src/pages/app/functions/mods/DebugPanel/QueryParamsTab/index.tsx
web/src/pages/app/functions/mods/DebugPanel/index.tsx

add params storage and code storage in runningCode
write code and params
running  (Click the button or Ctrl+s)
then the code and params  are stored on the server side

feat(web): add function params storage

---

cli/package-lock.json
cli/package.json
cli/src/action/deploy/index.ts
cli/src/schema/deploy.ts

feat(cli): add website deploy

---

.github/workflows/doc-preview.yml

complete  #1063 
* open/reopen PR: create bucket & website, deploy
* update PR: redeploy
* close PR: delete
link: https://github.com/aFlyBird0/laf/pull/4
1. blocked by #1469
2. GitHub Action Secrets to be added @maslow （Since informing users about the access address is necessary during the preview, app ID and other information will be exposed. It is recommended to use a completely **new, low-privileged application**.）
```yaml 
${{ secrets.LAF_CI_DOCS_PREVIEW_PAT }}
${{ secrets.LAF_CI_DOCS_PREVIEW_APPID }}
${{ secrets.LAF_CI_DOCS_PREVIEW_API_URL }}
```

ci: laf doc preview during pr

---

web/src/hooks/useAwsS3.ts
web/src/pages/app/storages/mods/CreateWebsiteModal/SiteStatus.tsx
web/src/pages/app/storages/mods/CreateWebsiteModal/index.tsx
web/src/pages/app/storages/mods/FileList/index.tsx
web/src/pages/app/storages/mods/StorageListPanel/index.tsx
web/src/pages/app/storages/store.ts

fix(web): fix storage list pagination & site available only storage readonly

---

server/src/initializer/initializer.service.ts
server/src/setting/entities/setting.ts

```js
use sys_db;
db.Setting.insertMany([{
public: true,
key: 'ai_pilot_url',
value: 'https://htr4n1.laf.run/laf-gpt',
desc: 'ai pilot url',
},
{
public: true,
key: 'laf_forum_url',
value: 'https://forum.laf.run',
desc: 'laf forum url',
},
{
public: true,
key: 'laf_business_url',
value: 'https://www.wenjuan.com/s/I36ZNbl',
desc: 'laf business url',
},
{
public: true,
key: 'laf_discord_url',
value: 'https://discord.com/channels/1061659231599738901/1098516786170839050',
desc: 'laf discord url',
},
{
public: true,
key: 'laf_wechat_url',
value: 'https://w4mci7-images.oss.laf.run/wechat.png',
desc: 'laf wechat url',
},
{
public: true,
key: 'laf_status_url',
value: 'https://hnpsxzqqtavv.cloud.sealos.cn/status/laf',
desc: 'laf status url',
},
]);
```

feat(server): add laf web site settings

---

cli/src/action/function/index.ts

fix(cli): fix read function name error in windows

---

server/src/initializer/initializer.service.ts
server/src/instance/instance.service.ts
server/src/region/entities/region.ts

```js
db.Region.updateMany(
{}, 
{
$set: {
"clusterConf.runtimeAffinity": {
"nodeAffinity": {
"requiredDuringSchedulingIgnoredDuringExecution": {
"nodeSelectorTerms": [
{
"matchExpressions": [
{
"key": "laf.dev/node.type",
"operator": "In",
"values": [
"runtime"
]
}
]
}
]
}
}
}
}
}
)
```

feat(server): add affinity settings in region

---

packages/cloud-sdk/src/function.interface.ts
runtimes/nodejs/src/handler/debug-func.ts
runtimes/nodejs/src/handler/invoke-func.ts
runtimes/nodejs/src/support/function-engine/types.ts

1.  复用拦截器上下文
2. ~~增加varMap用于挂载变量~~

feat(runtime): reuse context

---

build/charts/minio/templates/console-ingress.yaml

Add this annotation is use to enable websocket connections.
---

fix(build): minio console ingress enable websocket

---

runtimes/nodejs/src/config.ts
runtimes/nodejs/src/support/engine/module.ts

fix(runtime): default close module cache

---

runtimes/nodejs/src/handler/invoke.ts
runtimes/nodejs/src/support/engine/console.ts
runtimes/nodejs/src/support/utils.ts

path: `laf/runtimes/nodejs/src/handler/invoke.ts`
```js
if (
typeof result.data === 'object' &&
result.data.__type__ === '__interceptor__' &&
result.data.__res__ == false
) {
...
}
```
在函数返回null的时候会报错。

fix(runtime): object check

---

docs/guide/db/find.md
packages/database-ql/src/result-types.ts

```typescript
const res = await db.collection("user").doc("644148fd1eeb2b524dba499e").get()
console.log(res.data)    // it might be null
```
Just to make the type I mentioned above more accurate

doc: opt db-ql documents

---

.github/workflows/dockerize-runtime-exporter.yml
.github/workflows/dockerize-runtime-nodejs.yml
.github/workflows/dockerize-server.yml
.github/workflows/dockerize-web.yml

the pr is for handling image cache.
you could specify a unique image with the following method:
```
docker.io/lafyun/xxx:tag@digest
```

chore(ci): add digest for images of the pr

---

web/src/pages/app/functions/mods/HeadPanel/index.tsx

When cloud function name is directory like style, ( eg. /module1/sub1/sub3/read-func-name)
cloud function name display is inconvenient to read in Function head panel
only show func name of last depth may be a little better

chore: only show func name of last depth

---

web/public/locales/en/translation.json
web/public/locales/zh-CN/translation.json
web/public/locales/zh/translation.json
web/src/App.tsx
web/src/components/UpgradePrompt/index.tsx
web/tsconfig.json
web/vite.config.ts

feat(web): support version upgrade prompt

---

cli/src/schema/app.ts

1. laf storage push/pull
2. storage token expired (the error only happen in storage token `refesh`)
new schema of `app` by `console.log`
origin `.app.yaml`
`.app.yaml` after refresh

fix(cli): storage field key error during refresh

---

deploy/README.md
deploy/install-on-mac.sh

1. improve deploy/README.md
We have to grant Full Disk Access for multipassd after brew install. Otherwise, we will get an error like `sh:0: cannot open /laf/deploy/install-on-linux.sh: Operation not permitted`.
I wanted to upload an image but failed. Sorry.
2. improve shell echo
Echo 40G but 50G actually.

docs: improve macOS deploy guide

---

server/src/log/log.controller.ts

Keep sending empty messages so that log requests are not automatically disconnected

feat: log request server automatically send an empty message

---

web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx

feat(web): recommend function template config with templateid
