packages/system-server/src/handler/function/create.ts

The real verification should be the function name rather than the function label

fix create function validation fail

---

packages/system-client/src/views/application/index.vue

feat: opt index app_id format

---

packages/app-console/src/views/database/collections.vue

fix(app-console): fixed collection list height

---

packages/app-service/src/handler/invoke-func.ts

feat(app-service): support default cloud function

---

packages/app-console/src/views/storage/buckets.vue

feat: full bucket name

---

packages/gateway-controller/src/support/apisix-gateway-init.ts

fix route priority

---

packages/system-server/src/init.ts

fix: fix create system app error

---

vetur.config.js

Its useful open laf as root path in vscode
Reference: https://vuejs.github.io/vetur/reference/

chore: add vetur.config.js to define root config of vue3 root

---

packages/web/src/pages/app/[appid]/cloudfunction/[id].vue

add remove eventListener to fix multi event bind

fix: multi event bind

---

packages/web/src/components/FunctionEditor/index.vue
packages/web/src/components/JsonEditor/param.vue
packages/web/src/pages/app/[appid]/cloudfunction/[id].vue

fix: JsonEditor add min height & line numbers

---

packages/web/locales/en.yml
packages/web/locales/zh-CN.yml
packages/web/src/pages/app/[appid]/cloudfunction/logs/index.vue
packages/web/src/pages/app/[appid]/cloudfunction/triggers/[funcId].vue
packages/web/src/pages/app/[appid]/database/collections.vue

1. 添加 collection 数据为空时的显示
2. 增加秒的单位

Feat web function trigger

---

packages/web/locales/en.yml
packages/web/locales/zh-CN.yml
packages/web/src/layout/AppLayout.vue
packages/web/src/layout/components/Multitab/Tabs.vue
packages/web/src/layout/components/SideBar/index.vue
packages/web/src/layout/components/TopBar.vue
packages/web/src/pages/app/[appid]/cloudfunction/[id].vue

1. 添加菜单 i18n 和选中状态
2. 把 tabbar 放到头部位置，去掉头部之前的切换 app ，增加内容区域的占比

Feat web menu

---

docs/examples/wechat-pay.md

Signed-off-by: fanux <fanux@sealos.io>

add wechat native pay docs

---

docs/guide/function/index.md
packages/app-service/src/config.ts
packages/app-service/src/index.ts

This pr is fix [issue_234](https://github.com/labring/laf/issues/234).

Fix issue 234

---

packages/gateway-controller/src/config.ts
packages/gateway-controller/src/index.ts
packages/gateway-controller/src/scheduler.ts
packages/gateway-controller/src/support/apisix-gateway-init.ts
packages/gateway-controller/src/support/apisix-gateway-utils.ts
packages/gateway-controller/src/support/apisix-gateway.ts
packages/gateway-controller/src/support/db.ts
packages/gateway-controller/src/support/gateway-operator.ts
packages/gateway-controller/src/support/logger.ts
packages/gateway-controller/src/support/route.ts

1. merge ssl certificates into one
2. formatting gateway-contronller code style

feat: opt ssl create and code style

---

packages/app-service/src/support/function-engine/console.ts

fix: fix missing of console.warn/debug/info

---

controllers/database/controllers/database_controller.go
go.work
go.work.sum
pkg/util/string.go

1. add go workspace
2. move containsString to pkg/util

feat: add go workspace and move containsString to pkg/util

---

controllers/database/controllers/database_controller.go
controllers/database/controllers/store_controller.go
pkg/util/string.go

fix: add logs & fix finalizer deletion logic

---

controllers/oss/controllers/bucket_controller.go
controllers/oss/driver/minio.go

feat(oss): impl deletions logic for bucket

---

pkg/common/name.go
tests/README.md

doc: add testing design doc

---

docs/guide/function/index.md

- 新增`cloud.invoke`方法使用说明
- 新增`cloud.emit`方法使用说明
- 新增`cloud.shared`方法使用说明

docs: update functions.md

---

deploy/docker-compose/.env

updated .env file annotation

---

tests/util/template.go
tests/util/template_test.go

1. 用go模版渲染代替replaceAll生成yaml文件

feat(tests): add template render

---

controllers/gateway/api/v1/gateway_types.go
controllers/gateway/config/crd/bases/gateway.laf.dev_gateways.yaml
controllers/gateway/controllers/gateway_controller.go
controllers/gateway/tests/README.md
controllers/gateway/tests/api/domain.go
controllers/gateway/tests/api/domain_test.go
controllers/gateway/tests/api/gateway.go
controllers/gateway/tests/api/gateway_test.go
controllers/gateway/tests/api/oss.go
controllers/gateway/tests/api/oss_test.go
controllers/gateway/tests/api/route.go
controllers/gateway/tests/e2e/gateway_test.go
controllers/gateway/tests/e2e/route_test.go
tests/api/kubernetes.go

1. gateway add status condition
2. fix create route namespace
3. add gateway crd e2e test

feat(gateway): add gateway e2e test

---

deploy/kubernetes/README.md
deploy/kubernetes/ingress.yml

1. 对 deploy/kubernetes/ingress.yaml 的小修改，主要是修改resolver
2. 稍微补充了下 README.md

对 deploy/kubernetes/ingress.yaml 的小修改

---

controllers/database/api/v1/database_types.go
controllers/database/config/crd/bases/database.laf.dev_databases.yaml
controllers/oss/api/v1/bucket_types.go
controllers/oss/config/crd/bases/oss.laf.dev_buckets.yaml

pretty bucket&database kubectl column

---

controllers/runtime/controllers/function_controller.go
controllers/runtime/dbm/function.go
controllers/runtime/dbm/function_test.go
controllers/runtime/main.go
controllers/runtime/tests/api/function.go
pkg/util/hash.go
pkg/util/slice.go

1. impl impl function  crd controller

feat(runtime): impl function crd controller

---

docs/guide/index.md

docs: Update index.md

---

core/controllers/application/config/rbac/role.yaml
core/controllers/application/controllers/application_controller.go
core/controllers/application/main.go
core/controllers/gateway/controllers/domain_controller.go
core/controllers/oss/controllers/user_controller.go

fix(core): fix oss user namespace error, fix rbac for crd

---

.vscode/settings.json
server/src/applications/applications.controller.ts
server/src/applications/applications.service.spec.ts
server/src/applications/applications.service.ts
server/src/applications/dto/create-application.dto.ts
server/src/applications/dto/update-application.dto.ts
server/src/applications/entities/application.entity.ts
server/src/applications/entities/bundle.entity.ts
server/src/applications/entities/runtime.entity.ts
server/src/buckets/buckets.controller.ts
server/src/buckets/buckets.service.ts
server/src/buckets/dto/create-bucket.dto.ts
server/src/buckets/entities/bucket.entity.ts
server/src/common/getter.ts
server/src/common/response.ts
server/src/common/types.ts
server/src/constants.ts
server/src/core/kubernetes.interface.ts

feat(doc): refact entity & interfaces to support swagger struct

---

server/src/applications/applications.controller.ts
server/src/applications/applications.service.ts
server/src/applications/entities/application.entity.ts
server/src/functions/dto/create-function.dto.ts
server/src/functions/entities/function.entity.ts
server/src/functions/functions.controller.ts
server/src/functions/functions.module.ts
server/src/functions/functions.service.ts

feat(server): implement function creation

---

server/src/buckets/buckets.controller.ts
server/src/common/response.ts
server/src/functions/functions.controller.ts
server/src/functions/functions.service.ts

feat(server): implement function query apis

---

core/controllers/application/resourcer/database.go
server/package-lock.json
server/package.json
server/src/applications/applications.controller.ts
server/src/applications/applications.module.ts
server/src/applications/applications.service.ts
server/src/applications/entities/application.entity.ts
server/src/collections/collections.controller.ts
server/src/collections/collections.module.ts
server/src/collections/collections.service.ts
server/src/collections/database.service.spec.ts
server/src/collections/database.service.ts
server/src/collections/dto/create-collection.dto.ts
server/src/collections/entities/database.entity.ts

feat(server): implement collection creation api.

---

server/src/collections/collections.controller.ts
server/src/collections/collections.service.ts
server/src/collections/dto/update-collection.dto.ts
server/src/collections/entities/collection.entity.ts

feat(server): impl collection query, update, delete;

---

server/src/app.controller.ts
server/src/applications/applications.controller.ts
server/src/buckets/buckets.controller.ts
server/src/functions/functions.controller.ts
server/src/main.ts
server/src/policies/policies.controller.ts
server/src/websites/websites.controller.ts

chore(doc): organize the classification of api documents

---

deploy/scripts/README.md
server/package-lock.json
server/package.json
server/prisma/schema.prisma
server/src/app.controller.ts
server/src/applications/applications.controller.ts
server/src/auth/auth.service.ts
server/src/main.ts
server/src/users/users.service.ts

chore(server): update db schema & deploy doc

---

server/src/app.controller.ts
server/src/buckets/buckets.controller.ts
server/src/collections/collections.controller.ts
server/src/functions/functions.controller.ts
server/src/policies/policies.controller.ts
server/src/users/dto/user.response.ts
server/src/websites/websites.controller.ts

docs(server): improve api docs, add res dto, auth header, todo marker

---

deploy/charts/README.md
deploy/charts/casdoor/README.md
deploy/charts/casdoor/templates/init_data.yaml
deploy/charts/casdoor/values.yaml
deploy/scripts/install-k8s.sh
deploy/scripts/install-laf-core.sh

chore(deploy): fix hosts overwrite when ubuntu-restarting, fix casdoor redirect uri

---

server/src/main.ts

chore(server): fix to persist bearer auth in swagger ui

---

server/src/applications/applications.controller.ts
server/src/applications/applications.service.ts
server/src/applications/dto/create-application.dto.ts
server/src/applications/dto/update-application.dto.ts
server/src/applications/entities/application.entity.ts
server/src/functions/dto/create-function.dto.ts
server/src/functions/entities/function.entity.ts
server/src/functions/functions.controller.ts
server/src/functions/functions.service.ts

fix(server): fix app api error, fix dto & entity transform

---

server/src/applications/applications.service.ts
server/src/buckets/buckets.controller.ts
server/src/buckets/buckets.service.ts
server/src/buckets/dto/update-bucket.dto.ts
server/src/buckets/entities/bucket.entity.ts

feat(server): implement bucket update & deletion apis

---

deploy/scripts/README.md

如果不先install，直接执行`npx prisma db push` 会覆盖 package-lock.json

docs: add install step

---

core/controllers/application/resourcer/database.go
core/controllers/application/resourcer/oss.go

fix(core): fix oss cr name of app

---

server/prisma/schema.prisma
server/src/app.controller.spec.ts

design(server): add app, bundle, runtime db schema

---

server/prisma/schema.prisma
server/src/app.module.ts
server/src/applications/applications.controller.ts
server/src/applications/applications.module.ts
server/src/applications/applications.service.ts
server/src/auth/application.auth.guard.ts
server/src/buckets/buckets.controller.ts
server/src/buckets/buckets.module.ts
server/src/collections/collections.module.ts
server/src/common/types.ts
server/src/core/application.cr.service.ts
server/src/functions/functions.module.ts
server/src/users/dto/user.response.ts
server/src/users/users.service.ts

feat(server): implement & reafct app apis with server db

---

server/prisma/schema.prisma
server/src/applications/applications.controller.ts
server/src/auth/auth.service.ts
server/src/auth/casdoor.service.ts

fix(server): fix user db schema unique error

---

docs/guide/db/actions.md

docs: modified batch delete documentation and examples

---

.github/workflows/link-pr.yml
.github/workflows/link-schedule.yml
.lycheeignore
docs/package.json

Signed-off-by: Bird <aflybird0@gmail.com>
A CI which check broken links during PR and schedules every day.
close #466 
You could take a look of one "action run" at my fork repo:
https://github.com/aFlyBird0/laf/actions/runs/3600925045

ci: link check when pr and scheduled

---

server/package-lock.json
server/package.json
server/prisma/schema.prisma
server/src/common/lang.ts
server/src/constants.ts
server/src/core/function.cr.service.ts
server/src/functions/dto/create-function.dto.ts
server/src/functions/dto/update-function.dto.ts
server/src/functions/functions.controller.ts
server/src/functions/functions.module.ts
server/src/functions/functions.service.spec.ts
server/src/functions/functions.service.ts

feat(server): reafct cloud functions' apis in db

---

server/src/app.module.ts
server/src/constants.ts
server/src/initializer/initializer.module.ts
server/src/initializer/initializer.service.spec.ts
server/src/initializer/initializer.service.ts
server/src/main.ts

feat(server): add initializer module for init sys db

---

.github/workflows/build_cluster_images.yml
deploy/scripts/init-laf/runtime.yaml
runtimes/nodejs/Dockerfile
runtimes/nodejs/Dockerfile.init
runtimes/nodejs/build-image.sh
runtimes/nodejs/package-lock.json
runtimes/nodejs/package.json
runtimes/nodejs/src/cloud-sdk/index.ts
runtimes/nodejs/src/handler/invoke-func.ts
runtimes/nodejs/src/support/function-engine/function.ts
runtimes/nodejs/src/support/function-engine/types.ts
runtimes/nodejs/start.sh
server/build-image.sh
server/package.json

- feat(runtime): upgrade app runtime for v1.0.alpha
- build: add docker build shell for server & runtime

upgrade app runtime

---

web/components/Editor/FunctionEditor.tsx
web/components/Editor/JsonEditor.tsx
web/components/Editor/globalDefinition.ts
web/components/Layout/Function.tsx
web/constants/index.ts
web/pages/app/[app_id]/database/CollectionDataList/mods/ColPannel/index.tsx
web/pages/app/[app_id]/database/CollectionDataList/mods/IndexPannel/addIndexModal/index.tsx
web/pages/app/[app_id]/database/mods/CreateCollectionModal/index.tsx
web/pages/app/[app_id]/functions/index.tsx
web/pages/app/[app_id]/functions/mods/FunctionPanel/CreateModal/index.tsx
web/pages/app/[app_id]/functions/mods/FunctionPanel/index.tsx
web/pages/app/[app_id]/functions/store.ts
web/pages/globalStore.ts
web/pages/index.tsx
web/pages/mods/CreateAppModal/index.tsx
web/pages/mods/StatusBadge/index.tsx
web/services/v1/api-auto.d.ts
web/services/v1/apps.ts

Feat function page

---

.github/workflows/build-sealos-cluster-image.yml
.github/workflows/dockerize-controllers.yml
.github/workflows/dockerize-runtime-nodejs.yml
.github/workflows/dockerize-server.yml
.github/workflows/link-schedule.yml
.github/workflows/release.yml
core/controllers/database/Makefile
core/controllers/database/config/manager/kustomization.yaml
core/controllers/database/deploy/manifests/deploy.yaml
core/controllers/gateway/Makefile
core/controllers/gateway/config/manager/kustomization.yaml
core/controllers/gateway/deploy/manifests/deploy.yaml
core/controllers/oss/Makefile
deploy/build/manifests/laf-database-controller.yaml
deploy/build/manifests/laf-gateway-controller.yaml

- ci: update & debug for release ci
- ci: remove trigger condition

build(ci): add release ci workflows;

---

.github/workflows/build-sealos-cluster-image.yml
.github/workflows/dockerize-controllers.yml
.github/workflows/dockerize-runtime-nodejs.yml
.github/workflows/dockerize-server.yml

build(ci): fix workflow concurrency error

---

deploy/scripts/install-on-linux.sh
server/src/applications/specs.controller.ts
server/src/constants.ts
server/src/initializer/initializer.service.ts

fix(server): add region api, fix init image version

---

.github/workflows/dockerize-runtime-nodejs.yml
.github/workflows/dockerize-server.yml

build(ci): fix path mistake in workflow

---

core/controllers/gateway/controllers/gateway_controller.go

fix(core): fix app route serviceName and port

---

core/controllers/gateway/controllers/gateway_controller.go

feat(core): defalut enable websocket

---

.gitignore
deploy/build/Kubefile
deploy/build/charts/laf/charts/apisix/values.yaml
deploy/build/charts/laf/values.yaml
deploy/build/start.sh
deploy/scripts/install-on-linux.sh
deploy/scripts/install-on-mac.sh

build: support domain custom for deploy scripts

---

.github/workflows/build-scripts-updated.yml
.github/workflows/build-sealos-cluster-image.yml

build(ci): add workflow for build scripts updated

---

deploy/build/Kubefile
deploy/build/charts/laf/templates/NOTES.txt
deploy/build/charts/laf/templates/casdoor-ingress.yaml
deploy/build/charts/laf/templates/minio-ingress.yaml
deploy/build/charts/laf/values.yaml
deploy/build/start.sh
deploy/scripts/install-on-linux.sh

build(deploy): add ingress config for services

---

.github/workflows/dockerize-server.yml
deploy/build/charts/laf/charts/laf-server/.helmignore
deploy/build/charts/laf/charts/laf-server/Chart.yaml
deploy/build/charts/laf/charts/laf-server/templates/NOTES.txt
deploy/build/charts/laf/charts/laf-server/templates/_helpers.tpl
deploy/build/charts/laf/charts/laf-server/templates/deployment.yaml
deploy/build/charts/laf/charts/laf-server/templates/hpa.yaml
deploy/build/charts/laf/charts/laf-server/templates/ingress.yaml
deploy/build/charts/laf/charts/laf-server/templates/service.yaml
deploy/build/charts/laf/charts/laf-server/templates/serviceaccount.yaml
deploy/build/charts/laf/charts/laf-server/templates/tests/test-connection.yaml
deploy/build/charts/laf/charts/laf-server/values.yaml
deploy/build/charts/laf/values.yaml
docs/package.json
server/.dockerignore
server/Dockerfile
server/Dockerfile.alpine

build(deploy): add laf server helm chart, fix server dockerfile

---

core/controllers/gateway/controllers/domain_controller.go
core/controllers/gateway/controllers/secret_controller.go
core/controllers/gateway/main.go

feat(core): refresh apisix ssl

---

deploy/build/charts/laf/charts/laf-server/templates/service.yaml
deploy/build/charts/laf/charts/laf-server/values.yaml
deploy/build/charts/laf/templates/server-ingress.yaml
deploy/build/charts/laf/templates/web-ingress.yaml
web/.dockerignore
web/Dockerfile
web/package-lock.json
web/package.json

build(web): add dockerfile & ingress for web

---

deploy/build/charts/laf/charts/casdoor/templates/init_data.yaml
deploy/build/charts/laf/charts/laf-server/templates/deployment.yaml
deploy/build/charts/laf/values.yaml
server/.env
server/package.json
server/src/constants.ts
server/src/main.ts

build(server): remove helmet from server;fix casdoor init uri

---

core/controllers/gateway/config/rbac/role.yaml
core/controllers/gateway/controllers/secret_controller.go
core/controllers/gateway/deploy/manifests/deploy.yaml
deploy/build/charts/laf/charts/laf-server/templates/deployment.yaml
deploy/build/charts/laf/charts/laf-server/templates/serviceaccount.yaml
deploy/build/charts/laf/values.yaml
deploy/build/manifests/laf-gateway-controller.yaml
server/src/applications/application-task.service.ts
server/src/core/application.cr.service.ts
server/src/core/database.cr.service.ts
server/src/core/gateway.cr.service.ts
server/src/core/oss-user.cr.service.ts

- build(charts): fix sa config error of server charts
- fix(core: add rbac to gateway  secret controller

fix(core): fix rbac to gateway controller & fix sa config of server charts

---

core/controllers/gateway/controllers/route_controller.go

fix(core): gateway enable cors

---

core/controllers/gateway/api/v1/domain_types.go
core/controllers/gateway/api/v1/gateway_types.go
core/controllers/gateway/api/v1/route_types.go
deploy/build/charts/laf/templates/gateway-domain.yaml
server/src/core/bucket.cr.service.ts
server/src/core/gateway.cr.service.ts
server/src/storage/bucket.controller.ts
server/src/storage/storage.module.ts

feat(server): add bucket gateway management in server

---

web/.env
web/.env.production
web/Dockerfile
web/nginx.conf
web/src/utils/request.ts

build(web): update dockerfile & multi-env config for web

---

web/src/pages/app/functions/mods/FunctionPanel/index.tsx

fix: error when no function data

---

web/src/constants/index.ts
web/src/layouts/Function.tsx
web/src/pages/app/functions/index.tsx
web/src/pages/app/functions/mods/DeployButton/index.tsx
web/src/pages/globalStore.ts

1. add app restart feature
https://user-images.githubusercontent.com/972813/209057061-2296027e-2c63-45da-9ada-5aed77a4d1af.mov

feat(web): add app restart

---

web/src/apis/v2/dependence.ts
web/src/components/DepenceList/index.module.scss
web/src/components/DepenceList/index.tsx
web/src/pages/app/functions/mods/DependecePanel/AddDepenceModal/index.tsx
web/src/pages/app/functions/mods/DependecePanel/service.ts

Complete the dependent search list of the function

feat(web): add dependence

---

cli/package-lock.json
cli/package.json
cli/src/actions/application/application.ts
cli/src/apis/application.ts
cli/src/commands/application/application.ts
cli/src/main.ts
cli/src/templates/application.ts
cli/src/utils/constant.ts
cli/src/utils/path.ts
cli/src/utils/request.ts
cli/src/utils/token.ts
cli/tsconfig.json

feat(cli): init cli

---

cli/src/actions/application/application.ts
cli/src/actions/auth/auth.ts
cli/src/commands/auth/auth.ts
cli/src/main.ts
cli/src/templates/config.ts
cli/src/utils/constant.ts
cli/src/utils/path.ts
cli/src/utils/request.ts
cli/src/utils/token.ts

1. login and logout
2. update work dir

feat(cli): login and logout & update work dir

---

web/src/components/Editor/typesResolve/index.ts
web/src/components/IconWrap/index.tsx
web/src/layouts/Function.tsx
web/src/pages/app/functions/mods/FunctionPanel/index.tsx
web/src/pages/app/index.tsx
web/src/pages/app/mods/SiderBar/index.tsx
web/src/pages/globalStore.ts
web/src/pages/home/index.tsx
web/src/routes/index.tsx

feat(web): add custom url for page

---

core/controllers/gateway/controllers/gateway_controller.go

fix(core): remove bucket route pass host

---

web/src/hooks/useHotKey.ts
web/src/pages/app/functions/index.tsx
web/src/pages/app/functions/mods/DebugPannel/index.tsx
web/src/pages/app/functions/mods/DependecePanel/AddDepenceModal/index.tsx
web/src/pages/app/functions/mods/DependecePanel/index.tsx
web/src/pages/app/functions/mods/DependecePanel/service.ts
web/src/pages/app/functions/mods/DeployButton/index.tsx
web/src/pages/app/storages/mods/FileList/index.tsx
web/src/utils/format.ts

1. hide history request tab
2. fix hotKey bug
3. change OSS preview link( display when the interface is ready )
4. click the function debugging link to copy directly
5. system dependency cannot be deleted or edited(show tooltip)

feat(web): fix hotKey bug & hide some buttons

---

web/src/components/Editor/FunctionEditor.tsx
web/src/components/Editor/typesResolve/index.ts
web/src/components/Panel/Header.tsx
web/src/components/Panel/index.module.scss
web/src/pages/app/database/CollectionDataList/index.tsx
web/src/pages/app/database/CollectionDataList/mods/DataPannel/index.tsx

https://user-images.githubusercontent.com/972813/210399457-cd2548ac-8598-4956-af5d-5c928cfd16d9.mov

refactor(web): add loading function imports

---

web/.env
web/src/hooks/useHotKey.ts
web/src/pages/app/functions/mods/DebugPannel/index.tsx
web/src/pages/app/functions/mods/DeployButton/index.tsx
web/src/pages/home/mods/CreateAppModal/index.tsx
web/src/utils/hotKeyMap.ts

feat(web): optimize hotkey function

---

CHANGELOG.md
server/src/application/application.module.ts
server/src/application/application.service.ts
server/src/application/dto/create-env.dto.ts
server/src/application/environment.controller.ts
server/src/application/environment.service.ts

- feat(server): add enviroments apis
- chore: fix changelog links

feat(server): add enviroments apis

---

.vscode/settings.json
deploy/build/charts/laf/charts/laf-server/templates/deployment.yaml
server/.env
server/prisma/schema.prisma
server/src/app.controller.ts
server/src/application/application-task.service.ts
server/src/application/application.controller.ts
server/src/application/application.service.ts
server/src/constants.ts
server/src/initializer/initializer.service.ts
server/src/instance/instance.service.ts
server/src/main.ts
server/src/storage/storage.service.ts

- refactor(server): refactor region schema & apis
- deploy(server): update deploy charts

refactor(server): refactor region schema & apis

---

cli/src/action/function/index.ts
cli/src/command/function/index.ts

feat(cli): add function delete

---

cli/package-lock.json
cli/package.json
cli/src/api/debug.ts

修复包含中文的时候 `Invalid character in header content ["x-laf-func-data"]`

fix(cli): fix invalid debug header

---

packages/cloud-sdk/src/cloud.interface.ts

update env type under maslow's guidance

chore: update env in cloud-skd types

---

web/src/components/InputTag/index.tsx
web/src/pages/app/database/mods/AddRulesModal/index.tsx
web/src/pages/app/functions/mods/DebugPanel/index.tsx
web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
web/src/pages/app/functions/mods/FunctionPanel/index.tsx
web/src/pages/app/storages/mods/FileList/index.tsx
web/src/pages/app/storages/mods/StorageListPanel/index.tsx
web/src/pages/home/index.tsx
web/src/pages/home/mods/CreateAppModal/index.tsx
web/src/pages/home/mods/Empty/index.tsx
web/src/pages/home/mods/List/index.tsx

1. fix username when the home page is empty
2. refactor the layout of app list
3. fix edit app bug 
5. the methods could be empty when creating function

feat(web): fix home page & function page bugs

---

cli/src/action/application/index.ts
cli/src/config/secret.ts

fix invoke url error
todo: The http protocol is obtained from the parameter

fix(cli): fix invoke url error

---

cli/src/action/auth/index.ts
cli/src/common/constant.ts

fix(cli): fix login error

---

cli/src/action/application/index.ts
cli/src/action/policy/dto.ts
cli/src/action/policy/index.ts
cli/src/command/policy/index.ts
cli/src/common/constant.ts
cli/src/common/prompts.ts
cli/src/main.ts
cli/src/util/sys.ts

feat(cli): impl policy cmd

---

web/public/locales/en/translation.json
web/public/locales/zh-CN/translation.json
web/public/locales/zh/translation.json
web/src/App.tsx
web/src/components/IconText/index.tsx
web/src/layouts/Header/UserSetting/index.tsx
web/src/pages/app/database/CollectionDataList/index.tsx
web/src/pages/app/database/CollectionListPanel/index.tsx
web/src/pages/app/database/PolicyDataList/index.tsx
web/src/pages/app/database/PolicyListPanel/index.tsx
web/src/pages/app/database/index.tsx
web/src/pages/app/database/mods/DeleteCollectionModal/index.tsx
web/src/pages/app/database/service.ts
web/src/pages/app/functions/mods/BottomPanel/index.tsx
web/src/pages/app/functions/mods/DependencePanel/AddDependenceModal/index.tsx
web/src/pages/app/functions/mods/DeployButton/index.tsx
web/src/pages/app/functions/mods/FunctionPanel/index.tsx
web/src/pages/app/functions/service.ts
web/src/pages/app/setting/Profile/index.tsx
web/src/pages/app/setting/index.tsx
web/src/pages/app/storages/mods/CreateBucketModal/index.tsx
web/src/pages/app/storages/mods/CreateFolderModal/index.tsx
web/src/pages/app/storages/mods/DeleteBucketModal/index.tsx
web/src/pages/app/storages/mods/StorageListPanel/index.tsx
web/src/utils/i18n.ts

Feat add language switch

---

web/public/locales/en/translation.json
web/public/locales/zh-CN/translation.json
web/public/locales/zh/translation.json
web/src/pages/403.tsx
web/src/pages/app/functions/mods/DebugPanel/index.tsx
web/src/pages/home/mods/CreateAppModal/index.tsx
web/src/pages/home/mods/List/index.tsx
web/src/routes/index.tsx
web/src/utils/request.ts

feat(web): add 403 & 404 page

---

web/public/locales/en/translation.json
web/public/locales/zh-CN/translation.json
web/public/locales/zh/translation.json
web/src/components/Editor/JsonEditor.tsx
web/src/pages/app/database/mods/AddDataModal/index.tsx
web/src/pages/app/functions/mods/DebugPanel/BodyParamsTab/index.tsx
web/src/pages/app/functions/mods/DebugPanel/index.tsx
web/src/pages/customSetting.ts

support file upload to debug
https://user-images.githubusercontent.com/972813/218984994-bc8bdf86-146a-43bc-82f1-7e2a12fdd293.mov

feat(web): post debug add content type switch

---

web/public/locales/en/translation.json
web/public/locales/zh-CN/translation.json
web/public/locales/zh/translation.json
web/src/chakraTheme.ts
web/src/components/DotBadge/index.tsx
web/src/constants/index.ts
web/src/pages/app/functions/mods/TriggerModal/AddTriggerModal/index.tsx
web/src/pages/app/storages/mods/CreateBucketModal/index.tsx
web/src/pages/app/storages/mods/CreateWebsiteModal/SiteStatus.tsx
web/src/pages/app/storages/mods/CreateWebsiteModal/index.tsx
web/src/pages/app/storages/mods/FileList/index.tsx
web/src/pages/app/storages/mods/StorageListPanel/index.tsx

https://user-images.githubusercontent.com/972813/219389648-77f9c24f-8d92-45cb-ac10-d99e868e1e45.mov

feat(web): add website hosting custom domain

---

web/src/pages/home/mods/List/index.tsx

fix(web) : fix range of edit and delete buttons

---

cli/package.json
cli/src/action/storage/index.ts

1. fix #824 
2. remove aws-sdk

fix(cli): fix #824 win not cannot upload files normally

---

cli/package.json
cli/src/action/storage/index.ts
cli/src/action/storage/s3.ts

1. fix pr #831 multipath still has errors
3. temporary  shield aws sdk upgrade warn

fix(cli): fix multi-level path and shield aws upgrade warn

---

web/src/pages/app/storages/mods/CreateWebsiteModal/index.tsx
web/src/pages/app/storages/store.ts
web/src/utils/format.ts

fix(web) : add port for fileUrl and website

---

web/.swagger.config.js
web/src/apis/typing.d.ts
web/src/apis/v1/api-auto.d.ts
web/src/apis/v1/apps.ts
web/src/pages/app/functions/mods/DeployButton/index.tsx
web/src/pages/app/functions/mods/EditorPanel/index.tsx
web/src/pages/app/setting/AppInfoList/InfoDetail/index.module.scss
web/src/pages/app/storages/mods/CreateWebsiteModal/index.tsx
web/src/pages/app/storages/mods/FileList/index.tsx
web/src/pages/app/storages/service.ts
web/src/pages/app/storages/store.ts
web/src/pages/globalStore.ts
web/src/pages/home/mods/CreateAppModal/index.tsx
web/src/utils/format.ts

update(web): app create dialog

---

cli/package-lock.json
cli/src/action/function/index.ts
cli/src/action/website/index.ts
cli/src/api/debug.ts
cli/src/command/website/index.ts
cli/src/util/request.ts

1. remove private npm mirror
2. replace AxiosRequestConfig to any

fix(cli): remove private npm mirror and replace AxiosRequestConfig to any

---

cli/src/common/constant.ts

1. rename function meta file name
2. update default server address

feat(cli): rename name.meta.yaml to name.yaml

---

cli/package-lock.json
cli/package.json
cli/src/action/storage/index.ts
cli/src/action/storage/s3.ts

feat(cli): upgrade s3 sdk version

---

server/src/storage/dto/create-bucket.dto.ts
web/public/locales/en/translation.json
web/public/locales/zh-CN/translation.json
web/public/locales/zh/translation.json
web/src/pages/app/storages/mods/CreateBucketModal/index.tsx

fix(server): fix bucket name regex

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/question.yml
server/src/application/application.controller.ts
server/src/subscription/subscription.controller.ts

feat(server): add limit to update app state depends on subscription state

---

server/src/instance/instance.service.ts

fix(server): deal with existed app without namespace

---

server/src/application/dto/create-env.dto.ts

fix(server): add regex for environment name

---

.vscode/settings.json
server/src/instance/instance-task.service.ts

fix(server): stuck-starting instance blocked the task handler

---

cli/src/action/application/index.ts
cli/src/common/constant.ts

1. fix app url protocol error
2. update default url `laf.run`

fix: fix app url protocol error & update default url

---

deploy/scripts/install-on-linux.sh

optimize install-on-linux.sh

---

deploy/scripts/install-on-linux.sh

chore: sealos does not support pulling multiple cluster images

---

runtimes/nodejs/package.json
runtimes/nodejs/src/config.ts
runtimes/nodejs/src/constants.ts
runtimes/nodejs/src/db.ts
runtimes/nodejs/src/handler/db-proxy.ts
runtimes/nodejs/src/handler/debug-func.ts
runtimes/nodejs/src/handler/invoke-func.ts
runtimes/nodejs/src/handler/router.ts
runtimes/nodejs/src/handler/typings.ts
runtimes/nodejs/src/index.ts
runtimes/nodejs/src/support/cloud-sdk.ts
runtimes/nodejs/src/support/function-engine/cache.ts
runtimes/nodejs/src/support/function-engine/engine.ts
runtimes/nodejs/src/support/function-engine/function.ts
runtimes/nodejs/src/support/function-engine/index.ts
runtimes/nodejs/src/support/function-engine/require.ts
runtimes/nodejs/src/support/function-engine/types.ts
runtimes/nodejs/src/support/function-engine/vm.ts
runtimes/nodejs/src/support/logger.ts
runtimes/nodejs/src/support/policy.ts
runtimes/nodejs/src/support/token.ts
runtimes/nodejs/src/support/utils.ts

1. suport function import
2. cache function vm.script
3. prettier code style
@LeezQ Please help increase support for web prompts

feat(runtime): impl  cloud function import and cache function

---

docs/guide/client-sdk/index.md
docs/guide/quick-start/login.md

docs: update how to use the database

---

web/.env
web/src/components/Editor/typesResolve/globals.ts
web/src/components/Editor/typesResolve/requestType.ts
web/src/components/Editor/typesResolve/responseType.ts
web/src/components/Editor/typesResolve/streamType.ts
web/src/pages/app/functions/mods/FunctionPanel/CreateModal/functionTemplates.ts

- fix(web): opt ide typings for response & request
- fix(web): opt function templates codes

fix(web): opt ide typings for response & request, opt function templates

---

docs/guide/function/faq.md

(docs)修改错别字 “按照”=>"安装"

---

.github/workflows/deploy-doc.yml

run in my fork repo:
https://github.com/aFlyBird0/laf/actions/runs/4782640382
url preview: https://b033tj-laf-docs-main.site.laf.run/

ci: build and push laf doc

---

deploy/scripts/install-on-linux.sh

add iptables and host commands

doc: Update install-on-linux.sh add some install command

---

cli/template/gitignore

fix(cli): fix ignore file

---

cli/src/action/application/index.ts
cli/src/action/deploy/index.ts
cli/src/action/storage/index.ts
cli/src/action/user/index.ts
cli/src/api/pat.ts
cli/src/command/deploy/index.ts
cli/src/command/storage/index.ts
cli/src/command/user/index.ts
cli/src/common/constant.ts
cli/src/main.ts
cli/src/schema/app.ts
cli/src/schema/deploy.ts
cli/src/schema/function.ts
cli/src/schema/project.ts
cli/src/schema/user.ts
cli/tsconfig.json

feat(cli): add base deploy

---

.github/workflows/dockerize-server.yml
server/.dockerignore
server/Dockerfile

- chore: debug git hub actions
- debug dockerfile & actions

build: fix laf-server image build slowly

---

deploy/build/charts/apisix/values.yaml
server/src/gateway/apisix.service.ts
server/src/gateway/website-task.service.ts

1. support website history mode

feat(server): support website history

---

build/charts/apisix/values.yaml

update apisix-with-plugins version

chore: update apisix plugins version

---

cli/src/action/application/index.ts
cli/src/action/function/index.ts
cli/src/common/constant.ts
cli/src/schema/function.ts
cli/src/util/request.ts

1. add request error prompt 
2. opt init project

feat(cli): add error prompt & opt init project

---

cli/src/action/application/index.ts
cli/src/action/dependency/index.ts
cli/src/action/function/index.ts
cli/src/action/policy/index.ts
cli/src/schema/function.ts
cli/src/util/sys.ts

feat(cli): support specify code directory

---

cli/src/action/user/index.ts
cli/src/util/request.ts

fix(cli): fix remote url end with /

---

web/src/components/ChargeButton/index.tsx

* Unverified digits for balance recharge
* Clicking on the amount input field does not change
close #1256

fix(web): balance recharge

---

cli/src/action/application/index.ts
cli/src/action/function/index.ts
cli/src/command/function/index.ts

fix(cli): opt func pull command

---

web/src/components/ConfirmButton/index.tsx
web/src/pages/app/functions/mods/DependencePanel/AddDependenceModal/index.tsx
web/src/pages/app/functions/mods/DependencePanel/index.tsx

feat(web): support checking dep detail by jumping to `npmjs`

---

cli/src/action/application/index.ts
cli/src/command/application/index.ts

https://github.com/labring/laf/issues/1348
不知道用什么参数名合适, 暂时就想了一个`schema-only`

feat(cli): app init support schemaOnly

---

web/index.html
web/src/App.tsx
web/src/components/ChargeButton/index.tsx
web/src/layouts/Header/UserBalance/index.tsx
web/src/layouts/Header/index.tsx
web/src/pages/homepage/language.tsx
web/src/utils/format.ts

feat(web): add balance info at header

---

web/src/components/SectionList/index.module.scss
web/src/layouts/Template.tsx
web/src/pages/app/setting/UserInfo/Mods/PhoneEditor.tsx
web/src/pages/app/setting/UserInfo/Mods/UsernameEditor.tsx
web/src/pages/app/setting/UserInfo/index.tsx
web/src/pages/app/setting/index.tsx
web/src/pages/auth/reset-password/index.tsx

pages darkmode (function template, userinfo)
functions spacing
User Info

fix(web): fix function template darkmode & fix function spacing

---

web/src/components/DateRangePicker/index.tsx
web/src/pages/app/setting/BillingDetails/index.tsx
web/src/pages/app/setting/RechargeHistory/index.tsx
web/src/pages/app/setting/Usage/index.tsx
web/src/pages/app/setting/UserInvite/index.tsx
web/src/pages/auth/service.ts
web/src/pages/auth/signup/index.tsx

modify the redirection page after signup is completed to the dashboard page
loading state for the query

refactor(web): modify the redirection after signup to dashboard & add a loading state for the query

---

server/src/authentication/phone/phone.service.ts
server/src/authentication/user-passwd/user-password.service.ts
server/src/setting/entities/setting.ts

```js
use sys_db;
db.Setting.insertOne({
public: true,
key: 'invitation_profit',
value: '100',
desc: "Set up invitation rebate",
})
```

fix(server): fix invite code profit settings

---

web/src/components/DateRangePicker/index.tsx
web/src/pages/app/setting/AppEnvList/index.tsx
web/src/pages/app/setting/AppInfoList/InfoDetail/index.tsx
web/src/pages/app/setting/AppInfoList/index.tsx
web/src/pages/app/setting/Usage/index.tsx
web/src/pages/app/setting/index.tsx
web/src/pages/home/mods/StatusBadge/index.tsx

fix(web): fix ui & date range

---

web/src/chakraTheme.ts
web/src/chakraThemeDark.ts
web/src/components/IconText/index.tsx
web/src/pages/app/database/PolicyListPanel/index.tsx
web/src/pages/app/database/mods/DeleteCollectionModal/index.tsx
web/src/pages/app/functions/mods/FunctionPanel/index.tsx
web/src/pages/app/storages/mods/DeleteBucketModal/index.tsx
web/tailwind.config.cjs

Change the delete IconText color to red and completion the error color

---

web/public/locales/en/translation.json
web/public/locales/zh-CN/translation.json
web/public/locales/zh/translation.json
web/src/components/Markdown/index.tsx
web/src/components/SendSmsCodeButton/index.tsx
web/src/components/SmsCodeInput/index.tsx
web/src/layouts/Auth/index.tsx
web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
web/src/pages/app/setting/UserInfo/Mods/PasswordEditor.tsx
web/src/pages/app/setting/UserInfo/Mods/PhoneEditor.tsx
web/src/pages/app/setting/UserInfo/Mods/UsernameEditor.tsx
web/src/pages/auth/reset-password/index.tsx
web/src/pages/auth/signin/mods/LoginByPasswordPanel/index.tsx
web/src/pages/auth/signin/mods/LoginByPhonePanel/index.tsx
web/src/pages/auth/signup/index.tsx

refactor(web): use react-hook-form  & modify styles & add laf-ai apply button

---

web/public/locales/en/translation.json
web/public/locales/zh-CN/translation.json
web/public/locales/zh/translation.json
web/src/apis/typing.d.ts
web/src/components/SendSmsCodeButton/index.tsx
web/src/pages/app/setting/UserInfo/Mods/PasswordEditor.tsx
web/src/pages/app/setting/UserInfo/Mods/PhoneEditor.tsx
web/src/pages/auth/reset-password/index.tsx
web/src/pages/functionTemplate/Mods/TemplateInfo/index.tsx
web/src/pages/functionTemplate/Mods/UseTemplateModal/index.tsx

fix reset phone smscode type
& 
add function template developer info

fix(web): fix reset phone smscode type

---

cli/src/action/dependency/index.ts
cli/src/action/deploy/index.ts
cli/src/command/dependency/index.ts

在做template的时候, 为了方便deploy脚本, 增加两个option:
https://github.com/laflabs/laf-template-bundle

feat(cli): add options for laf dep command

---

web/src/constants/index.ts
web/src/pages/home/mods/StatusBadge/index.tsx

feat(web): add app realeasing status

---

cli/src/action/trigger/index.ts
cli/src/command/trigger/index.ts
cli/src/main.ts

feat(cli): impl trigger command

---

web/src/components/FileUpload/index.tsx
web/src/pages/app/storages/mods/UploadButton/index.tsx

fix(web): fix drag upload folder

---

cli/src/action/function/index.ts
cli/src/command/function/index.ts
cli/src/schema/function.ts

feat(cli): support multi folder & path

---

cli/src/util/sys.ts

fix(cli): fix cannot read properties baseDir

---

web/src/pages/app/mods/StatusBar/index.tsx
web/src/pages/home/mods/CreateAppModal/AutoscalingControl/index.tsx
web/src/pages/home/mods/CreateAppModal/BundleControl/index.tsx
web/src/pages/home/mods/CreateAppModal/index.tsx

split create app modal & fix some bugs

fix(web): fix statusbar change app specific display

---

.github/actions/build-docs/action.yml
.github/workflows/deploy-doc.yml
.github/workflows/link-pr.yml
.github/workflows/link-schedule.yml
.lycheeignore

* extract a local action to reuse `docs build` steps
* ~~fix build error caused by vitepress version **in temp** (can not work in latest vitepress@v1.0.0-rc4)~~
* little update about lychee

ci(docs): refactor docs build action

---

web/public/locales/en/translation.json
web/public/locales/zh-CN/translation.json
web/public/locales/zh/translation.json
web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
web/src/pages/app/functions/mods/FunctionPanel/index.tsx
web/src/pages/app/functions/mods/VersionHistoryPanel/index.tsx
web/src/pages/app/mods/SideBar/index.tsx

& change img to link
& add function history tips

fix(web): keep function expanded when making modifications

---

runtimes/nodejs/src/support/function-engine/cache.ts
runtimes/nodejs/src/support/function-engine/engine.ts
runtimes/nodejs/src/support/function-engine/require.ts
runtimes/nodejs/src/support/function-engine/types.ts
runtimes/nodejs/src/support/function-engine/vm.ts

feat(runtime): check circular dependency

---

runtimes/nodejs/src/config.ts
runtimes/nodejs/src/support/db-change-stream.ts
runtimes/nodejs/src/support/function-engine/cache.ts

close事件会被同时多次触发，增加只允许某时间间隔内一个change stream重连调用

fix: fix change stream concurrency reconnect

---

docs/guide/quick-start/login.md

doc: fix login example param checking

---

web/src/pages/app/database/CollectionListPanel/index.tsx

feat(web): collection list sort

---

server/src/account/account.service.ts
server/src/initializer/initializer.service.ts
server/src/setting/entities/setting.ts

```js
use sys_db;
db.Setting.insertOne({
public: false,
key: 'signup_bonus',
value: '0',
desc: 'Set up signup bonus',
});
```

feat(server): add signup profit

---

cli/src/action/database/index.ts
cli/src/action/function/index.ts
cli/src/api/custom.ts
cli/src/api/v1/account.ts
cli/src/api/v1/application.ts
cli/src/api/v1/authentication.ts
cli/src/api/v1/billing.ts
cli/src/api/v1/data-contracts.ts
cli/src/api/v1/database.ts
cli/src/api/v1/function.ts
cli/src/api/v1/functiontemplate.ts
cli/src/api/v1/group.ts
cli/src/api/v1/monitor.ts
cli/src/api/v1/public.ts
cli/src/api/v1/recyclebin.ts
cli/src/api/v1/user.ts
cli/src/command/database/index.ts
cli/src/main.ts
cli/src/util/request.ts

feat(cli): support database export and import

---

web/src/pages/app/functions/mods/DependencePanel/index.tsx

fix bug with delete button covered by scrollbar in npm dependency list area on #1546

fix(web): fix style in npm deps list area (#1546)

---

web/src/pages/app/functions/mods/FunctionPanel/index.tsx

fix(web): fix function list folder name display

---

build/start.sh

Finally, install Laf-web and enter the access address

chore(build): optimize installation sequence

---

runtimes/nodejs/src/support/engine/cache.ts
runtimes/nodejs/src/support/engine/module.ts

fix(runtime): fix update function not effective

---

build/start.sh

fix for multiple prometheus replicas which cause inconsistent return data

chore(build): change prometheus url

---

server/src/gateway/runtime-domain.service.ts
server/src/website/website.service.ts

fix(server): set deleting phase when deleting app

---

package-lock.json
package.json
runtimes/nodejs/README.md
runtimes/nodejs/package-lock.json
runtimes/nodejs/package.json
runtimes/nodejs/src/config.ts
runtimes/nodejs/src/handler/invoke.ts
runtimes/nodejs/src/index.ts
runtimes/nodejs/src/storage-server.ts
runtimes/nodejs/src/support/engine/cache.ts
runtimes/nodejs/src/support/engine/console.ts
runtimes/nodejs/src/support/engine/function.ts
runtimes/nodejs/src/support/engine/module.ts
runtimes/nodejs/src/support/engine/types.ts
runtimes/nodejs/src/support/engine/utils.ts
runtimes/nodejs/src/support/ws.ts
server/src/gateway/ingress/runtime-ingress.service.ts

重构日志
在header中返回debug日志
```
X-Laf-Func-Logs: ["2023-10-30 21:19:26.657 +08:00 'Hello World'","2023-10-30 21:19:26.657 +08:00 'Hello World2'","2023-10-30 21:19:26.657 +08:00 'Hello World3'","2023-10-30 21:19:26.658 +08:00 3"]
```

feat(runtime): refactor log console & enable module cache

---

web/public/locales/en/translation.json
web/public/locales/zh-CN/translation.json
web/public/locales/zh/translation.json
web/src/components/FileUpload/index.tsx
web/src/pages/app/storages/mods/UploadButton/index.tsx

fix(web): fix upload file entry 100 items limit

---

runtimes/nodejs/src/support/engine/function.ts

修复拦截器以main命名 云函数以default命名覆盖问题

fix(runtime): fix interceptor main func error

---

.github/workflows/build-sealos-cluster-image.yml
.github/workflows/doc-preview.yml
.github/workflows/dockerize-runtime-exporter.yml
.github/workflows/dockerize-runtime-nodejs.yml
.github/workflows/dockerize-server.yml
.github/workflows/dockerize-web.yml

- chore: debug runtime github action workflow
- commit pr to test workflows of runtime
- debug comment to pr
- test pr for server workflow
- update workflows for server & web
- add permission of pr in workflows
- debug permissions
- fix permissions in workflows

chore(build):  update github workflows to build images for pr events

---

packages/cloud-sdk/package-lock.json
packages/cloud-sdk/package.json
packages/cloud-sdk/src/storage.ts
runtimes/nodejs/package-lock.json
runtimes/nodejs/package.json

- feat(cloud-sdk): add filename url api to cloud.storage.bucket
- update cloud sdk version in runtime
- update cloud sdk version in runtime

feat(cloud-sdk): add url api to cloud sdk

---

cli/src/command/environment/index.ts

fix cli env command description

fix(cli): fix cli env command description

---

web/public/locales/en/translation.json
web/public/locales/zh-CN/translation.json
web/public/locales/zh/translation.json
web/src/components/ChargeButton/index.tsx
web/src/components/Resize/index.tsx
web/src/hooks/useResizable.ts
web/src/pages/app/database/index.tsx
web/src/pages/app/functions/index.tsx
web/src/pages/app/functions/mods/DebugPanel/index.tsx
web/src/pages/app/functions/mods/FunctionPanel/index.tsx
web/src/pages/app/functions/mods/TriggerModal/AddTriggerModal/index.tsx
web/src/pages/app/functions/mods/TriggerModal/index.tsx
web/src/pages/app/functions/mods/TriggerModal/service.ts
web/src/pages/app/mods/StatusBar/LogsModal/index.tsx
web/src/pages/app/setting/SysSetting/AppMonitor/PieCard/index.tsx
web/src/pages/app/setting/SysSetting/CustomDomain/index.tsx
web/src/pages/app/setting/UserSetting/BillingDetails/index.tsx
web/src/pages/app/setting/UserSetting/RechargeHistory/index.tsx
web/src/pages/app/setting/index.tsx
web/src/pages/app/storages/index.tsx
web/src/pages/app/storages/mods/CreateBucketModal/index.tsx
web/src/pages/app/storages/mods/CreateWebsiteModal/index.tsx
web/src/pages/app/storages/mods/StorageListPanel/index.tsx
web/src/pages/auth/signin/index.tsx
web/src/pages/customSetting.ts
web/src/pages/globalStore.ts
web/src/pages/home/mods/List/index.tsx

web各类样式问题 + web 提示优化
& 
add running cancel button

chore(web): fix styles & optimize tips & add running cancel

---

web/package-lock.json
web/package.json
web/public/locales/en/translation.json
web/public/locales/zh-CN/translation.json
web/public/locales/zh/translation.json
web/src/components/ConfirmDialog/index.tsx
web/src/hooks/useAwsS3.ts
web/src/pages/app/storages/mods/FileList/index.tsx
web/src/pages/globalStore.ts

Feature:
1. press `ctrl/cmd + a` to select all listed files
2. press `ctrl/cmd/option/alt + click` to select multiple files
3. press `delete` to delete selected files
Change:
1. double click to view a dir or preview a file.
All the feats or changes are similar to the local files system we use.

feat(web): support deleting multiple storage files

---

deploy/install-on-linux.sh

Update install-on-linux.sh change the sealos version 4.3.7

chore: install-on-linux.sh change the sealos version 4.3.7

---

build/charts/laf-server/templates/deployment.yaml
build/charts/laf-server/values.yaml
build/start.sh
server/src/application/application.controller.ts
server/src/constants.ts
server/src/initializer/deploy-manifest/database.yaml
server/src/initializer/initializer.service.ts
server/src/region/entities/region.ts
server/src/region/region.service.ts
web/public/locales/en/translation.json
web/public/locales/zh-CN/translation.json
web/public/locales/zh/translation.json
web/src/apis/typing.d.ts
web/src/pages/app/mods/StatusBar/MonitorBar/index.tsx
web/src/pages/home/mods/CreateAppModal/DatabaseBundleControl/index.tsx
web/src/pages/home/mods/CreateAppModal/index.tsx

feat(web&server): control the activation of the ddb & change the location of deploy manifests

---

server/nest-cli.json
server/src/initializer/initializer.service.ts

fix(server): read manifests failed when init region

---

web/package-lock.json
web/package.json
web/src/components/ConfirmButton/index.tsx
web/src/components/DateRangePicker/index.tsx
web/src/components/MoreButton/index.tsx
web/src/pages/app/functions/mods/FunctionPanel/ContextMenu/index.scss
web/src/pages/app/functions/mods/FunctionPanel/ContextMenu/index.tsx
web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
web/src/pages/app/functions/mods/FunctionPanel/index.tsx
web/src/pages/app/functions/service.ts
web/src/pages/app/setting/UserSetting/BillingDetails/index.tsx
web/src/pages/app/setting/UserSetting/RechargeHistory/index.tsx
web/src/pages/app/setting/UserSetting/index.tsx

feat(web): add function list context menu

---

web/public/locales/en/translation.json
web/public/locales/zh-CN/translation.json
web/public/locales/zh/translation.json
web/src/pages/app/functions/mods/DependencePanel/AddDependenceModal/index.tsx
web/src/pages/app/storages/store.ts

fix(web): fix storage path concatenation & add dependency install tip

---

web/src/pages/app/database/PolicyDataList/index.tsx
web/src/pages/app/database/PolicyListPanel/index.tsx

fix(web): add database policy add modal back

---

docs/zh/quick-start/login.md

Docs guide tutorial still use old database syntax,so update.

chores(docs): Update login.md

---

runtimes/nodejs/src/support/module-hot-reload.ts

fix(runtime): zombie processes caused by inappropriate way of dependencies

---

server/src/gateway/ingress/bucket-ingress.service.ts

fix(server):Fix ingress creation failure on non-standard ports 
